### ISSUE TITLE
User-Courses Endpoint

### ISSUE THREAD

**Issue by whuang8** [Groupr-Purdue/Groupr#14]
## Task
- [x] Create endpoint to display the enrolled courses of a specific user - GET /users/:id/courses
- [x] Create endpoint to display the users of a given course - GET /courses/:id/users
- [x] Create endpoint to enroll a user in a course - POST /courses/:id/users

**Comment by ZachPurdue** [comment]
I think this issue has been fixed with the latest merge
